version: '3'

tasks:
  build:
    desc: "Собрать Docker-контейнеры"
    cmds:
      - docker compose build

  up:
    desc: "Запустить контейнеры"
    cmds:
      - docker compose up -d

  run: 
    desc: "Собрать Docker и запустить контейнеры"
    deps: [build, up]

  down:
    desc: "Остановить контейнеры"
    cmds:
      - docker compose down

  integration:
    desc: "Запустить интеграционные тесты"
    cmds:
      - go test -v ./internal/tests

  test:
    desc: "Запустить юнит тесты"
    cmds:
      - go test -v ./internal/service
      - go test -v ./internal/auth
  
  cover:
    desc: "Запустить тест покрытия в html"
    cmds:
      - go test ./... -coverprofile c.out
      - go tool cover -html=c.out

  check:
    desc: "Запустить все тесты"
    deps: [test, integration]    

  restart:
    desc: "Перезапустить контейнеры"
    cmds:
      - docker compose down
      - docker compose up -d